repos:
  - repo: git@github.com:PyCQA/autoflake.git
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports' ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        args: [ ".env", "README.md" ]
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ --line-length, '120' ]
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
      - id: bandit
        args: [ '--ini', '.bandit', '-r' ]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        exclude: ^migrations/
        args:
          [
            "--rcfile=.pylintrc",
            "-rn",
            "-sn",
            "--max-line-length=120"
          ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        args: ['--ignore=42194']
